version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: tarefa-postgres
    restart: always
    environment:
      POSTGRES_USER: tarefa
      POSTGRES_PASSWORD: tarefa123
      POSTGRES_DB: tarefadb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: