spring.application.name=tarefa-api-server
server.port=8080

# =============================================================
# POSTGRESQL
# =============================================================
# URL JDBC — jdbc:postgresql://HOST:PORTA/NOME_DO_BANCO
spring.datasource.url=jdbc:postgresql://localhost:5432/tarefadb
spring.datasource.username=tarefa
spring.datasource.password=tarefa123
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================================
# JPA / HIBERNATE
# =============================================================
# Dialeto específico do PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# update: cria tabelas que não existem e adiciona colunas novas,
# mas NUNCA apaga dados. Os dados persistem entre reinícios da aplicação.
# Em produção use "validate" ou "none".
spring.jpa.hibernate.ddl-auto=update

# Mostra as queries SQL no console — útil para aprender
spring.jpa.show-sql=true

# =============================================================
# SWAGGER
# =============================================================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.doc-expansion=list